version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML"

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Building static HTML site"
      - mkdir -p output
      # Copy all files except 'output' dir and current dir
      - find . -maxdepth 1 ! -name 'output' ! -name '.' -exec cp -r {} output/ \;
      - rm -f output/buildspec.yml

  post_build:
    commands:
      - echo "Build complete - $(ls -la output/)"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id EV48OR3A5JZD9 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
