version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML"

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Building static HTML site"
      - mkdir -p output
      # Exclude output directory itself from being copied
      - shopt -s extglob
      - cp -r !(output) output/
      - rm -f output/buildspec.yml

  post_build:
    commands:
      - echo "Build complete - $(ls -la output/)"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id YOUR_REAL_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
